# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('que1', models.IntegerField(default=1)),
                ('que2', models.IntegerField(default=1)),
                ('que3', models.IntegerField(default=1)),
                ('que4', models.IntegerField(default=1)),
                ('que5', models.IntegerField(default=1)),
                ('ans1', models.IntegerField(default=1)),
                ('ans2', models.IntegerField(default=1)),
                ('ans3', models.IntegerField(default=1)),
                ('ans4', models.IntegerField(default=1)),
                ('ans5', models.IntegerField(default=1)),
                ('state', models.IntegerField(default=0)),
                ('conn', models.IntegerField(default=0)),
                ('conn_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
