# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='conn_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
