# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170903_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission1', models.IntegerField(default=0)),
                ('submission2', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='Sub',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='peers',
            field=models.IntegerField(default=0),
        ),
    ]
