# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20170908_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time1',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='submission',
            name='time2',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='submission',
            name='time3',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='submission',
            name='time4',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='submission',
            name='time5',
            field=models.TimeField(default='00:00'),
        ),
    ]
